# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5083e0ee62e71ded77f427db7a9b42dfc132e4dac3f9f60376c0fccdb4a00273a3d7c1af82e33edb687d1656e3f6ed31a3dee61186b7859db6d0081cf1712ad8

test:
  secret_key_base: 9dc29528c1cd32ba336fae1f9f164da3cd08ea6449976aabf5aed740f89b5f7254063aa539b640fffe045cccc4b36dab7e0f95b416112a21ccc137caf1fe3a3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
